SWybor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'views.bad_request'
# handler403 = 'views.permission_denied'
# handler404 = 'views.page_not_found'
# handler500 = 'views.server_error'

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^profile/', include('profuzyt.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^maps/', include('maps.urls')),
    url(r'^news/', include('blog.urls')),
   
]

blog/urls.py
# ~*~ coding: utf-8 ~*~

from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.main_page, name='main'),
    #url(r'^$', main_page),
    # Если передан id поста, то отдаем управление get_post вьюхе
   url(r'^post/([0-9]{1,5})', views.get_post,name='post'),
    #url(r'^post/([0-9]{1,5})', views.poll_summary, name='summary'),
    
]

profuzyt/urls.py
from django.conf.urls import url

from . import views

app_name = 'profuzyt'
urlpatterns = [
    url(r'^$', views.profile_view, name='profile'),
]

profuzyt/models.py
from django.db import models

profuzyt/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import re

class ProfileForm(forms.Form):
    firstname = forms.CharField(label='Imię', required=False, max_length=30)
    lastname = forms.CharField(label='Nazwisko', required=False, max_length=30)
    email = forms.CharField(label='Adres e-mail', required=False)

    firstname_regex = re.compile("^[ĘÓĄŚŁŻŹĆŃA-Z][ęóąśłżźćńa-z]+$")
    lastname_regex = re.compile("^[ĘÓĄŚŁŻŹĆŃA-Z][ęóąśłżźćńa-z]+$")

    def clean_firstname(self):
        data = self.cleaned_data['firstname']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.firstname_regex.match(data):
            raise forms.ValidationError(
                "Niepoprawny format imienia."
            )
        return data

    def clean_lastname(self):
        data = self.cleaned_data['lastname']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.lastname_regex.match(data):
            raise forms.ValidationError(
                "Niepoprawny format nazwiska."
            )
        return data

    def clean_email(self):
        data = self.cleaned_data['email']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        try:
            validate_email(data)
        except ValidationError as e:
            raise forms.ValidationError(
                "Nie poprawny adres e-mail."
            )
        return data

class PasswordChangeForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label='Hasło', required=False, max_length=30)
    repeatpassword = forms.CharField(widget=forms.PasswordInput, label='Powtórz hasło', 
        required=False, max_length=30)

    password_regex = re.compile("^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@.\+\-_])[A-Za-z\d@.+-_]+$")
    min_password_length = 6

    def clean_password(self):
        data = self.cleaned_data['password']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.password_regex.match(data):
            raise forms.ValidationError(
                "Hasło może się składać tylko z liter, dużych liter, cyfr i @/./+/-/_ " + 
                "i musi mieć po jednym z tych znaków."
            )
        if len(data) < self.min_password_length:
            raise forms.ValidationError(
                "Długośc hasła musi mieć mieć minimum 6 znaków."
            )
        
        return data

    def clean_repeatpassword(self):
        data = self.cleaned_data['repeatpassword']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if 'password' in self.cleaned_data and data != self.cleaned_data['password']:
            raise forms.ValidationError(
                "Podane hasła muszą do siebie pasować."
            )
        return data

profuzyt/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import Http404
from .forms import ProfileForm, PasswordChangeForm

def profile_view(request):
    if not request.user.is_authenticated():
        raise Http404

    email_exists = False
    if request.method == "POST":
        if 'password_change_button' in request.POST:
            user = request.user
            form_pass = PasswordChangeForm(request.POST)
            form = ProfileForm({'firstname': user.first_name, 'lastname': user.last_name, 'email': user.email})
            if form_pass.is_valid():
                password = form_pass.cleaned_data['password']
                user = request.user
                user.set_password(password)
                user.save()
        else:
            form_pass = PasswordChangeForm()
            form = ProfileForm(request.POST)
            if form.is_valid():
                firstname = form.cleaned_data['firstname']
                lastname = form.cleaned_data['lastname']
                email = form.cleaned_data['email']
                user = request.user
                if user.email != email and email in User.objects.all().values_list('email', flat=True):
                    email_exists = True
                else:
                    user.first_name = firstname
                    user.last_name = lastname
                    user.email = email
                    user.save()
    else:
        user = request.user
        form = ProfileForm({'firstname': user.first_name, 'lastname': user.last_name, 'email': user.email})
        form_pass = PasswordChangeForm()

    return render(request, 'profuzyt/profile.html', {'form': form, 'form_pass': form_pass,
        'email_exists': email_exists})

profuzyt/templates/profuzyt/profile.html
{% extends "base.html" %}

{% block title %}
    Ustawienia profilu
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <form action="{% url 'profuzyt:profile' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.firstname.label }}:
                {% render_field form.firstname class="form-control" %}
            </div>
        </div>
        {% if form.firstname.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.firstname.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.lastname.label }}:
                {% render_field form.lastname class="form-control" %}
            </div>
        </div>
        {% if form.lastname.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.lastname.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.email.label }}:
                {% render_field form.email class="form-control" %}
            </div>
        </div>
        {% if form.email.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.email.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        {% if email_exists %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    * Istnieje już użytkownik z takim adresem e-mail!<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center item">
                <input type="submit" name="profile_change_button" value="Zmień dane profilu" class="btn btn-primary">
            </div>
        </div>
        <div class="row"></div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form_pass.password.label }}:
                {% render_field form_pass.password class="form-control" %}
            </div>
        </div>
        {% if form_pass.password.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form_pass.password.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form_pass.repeatpassword.label }}:
                {% render_field form_pass.repeatpassword class="form-control" %}
            </div>
        </div>
        {% if form_pass.repeatpassword.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form_pass.repeatpassword.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center item">
                <input type="submit" name="password_change_button" value="Zmień hasło" class="btn btn-danger">
            </div>
        </div>
    </form>
{% endblock %}