SWybor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'views.bad_request'
# handler403 = 'views.permission_denied'
# handler404 = 'views.page_not_found'
# handler500 = 'views.server_error'

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^profile/', include('profuzyt.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^maps/', include('maps.urls')),
    url(r'^news/', include('blog.urls')),
   
]

blog/urls.py
# ~*~ coding: utf-8 ~*~

from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.main_page, name='main'),
    #url(r'^$', main_page),
    # Если передан id поста, то отдаем управление get_post вьюхе
   url(r'^post/([0-9]{1,5})', views.get_post,name='post'),
    #url(r'^post/([0-9]{1,5})', views.poll_summary, name='summary'),
    
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^create/$', views.create_poll_view, name='create'),
    url(r'^active/$', views.ActivePollView.as_view(), name='active'),
    url(r'^ended/$', views.EndedPollView.as_view(), name='ended'),
    url(r'^incoming/$', views.IncomingPollView.as_view(), name='incoming'),
    url(r'^(?P<poll_id>[1-9][0-9]*)/$', views.poll_option_view, name='option'),
    url(r'^(?P<poll_id>[1-9][0-9]*)/summary/$', views.poll_summary, name='summary'),
    url(r'^(?P<poll_id>[1-9][0-9]*)/vote/$', views.vote_view, name='vote'),
    url(r'^(?P<poll_id>[1-9][0-9]*)/vote/make/$', views.vote, name='votemake'),
    url(r'^mypolls/$', views.MyPollsView.as_view(), name='mypolls'),
    url(r'^(?P<poll_id>[1-9][0-9]*)/change/$', views.change_poll_view, name='change'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

class Poll(models.Model):
    name = models.CharField(max_length=50)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_start = models.DateTimeField()
    vote_end = models.DateTimeField()
    max_vote_number = models.DecimalField(decimal_places=0, max_digits=5)
    def __str__(self):
        return self.name

class PollOption(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "Poll:{ " + self.poll.__str__() + " }, Candidate:{ " + self.candidate.__str__() + " }"

class Vote(models.Model):
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    option = models.ForeignKey(PollOption, on_delete=models.CASCADE)
    def __str__(self):
        return "Voter:{ " + self.voter.__str__() + " }, Option:{ " + self.option.__str__() + " }"

class Authorized(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "Poll:{ " + self.poll.__str__() + " }, User:{ " + self.user.__str__() + " }"

polls/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.utils.timezone import localtime
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from .models import *
from .forms import PollCreateForm, PollChangeForm, StartedPollChange, PollUsersChange
from .fusioncharts import FusionCharts
from .custom_functions import to_ascii

class ActivePollView(generic.ListView):
    context_object_name = 'active_polls_list'
    template_name = 'polls/active.html'
    def get_queryset(self):
        return Poll.objects.filter(vote_start__lte=timezone.now(),vote_end__gte=timezone.now())

class EndedPollView(generic.ListView):
    context_object_name = 'ended_polls_list'
    template_name = 'polls/ended.html'
    def get_queryset(self):
        return Poll.objects.filter(vote_end__lt=timezone.now())

class IncomingPollView(generic.ListView):
    context_object_name = 'incoming_polls_list'
    template_name = 'polls/incoming.html'
    def get_queryset(self):
        return Poll.objects.filter(vote_start__gt=timezone.now())

def vote_view(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    vote_timeout = False
    too_many_options = False
    no_options = False
    if timezone.now() < poll.vote_start:
        if poll.creator == request.user:
            return change_poll_view(request, poll_id)
        raise Http404
    if timezone.now() > poll.vote_end:
        vote_timeout = True
    return render(request, 'polls/vote.html', {'vote_timeout': vote_timeout, 
        'too_many_options': too_many_options, 'no_options': no_options, 'poll': poll})

def vote(request, poll_id):
    vote_timeout = False
    too_many_options = False
    no_options = False
    poll = get_object_or_404(Poll, pk=poll_id)
    if timezone.now() < poll.vote_start:
        raise Http404
    user_options = request.POST.getlist('option')
    if timezone.now() > poll.vote_end:
        vote_timeout = True
    if len(user_options) > poll.max_vote_number:
        too_many_options = True
    if len(user_options) == 0:
        no_options = True
    if vote_timeout == True or too_many_options == True or no_options == True:
        return render(request, 'polls/vote.html', {'vote_timeout': vote_timeout, 
            'too_many_options': too_many_options, 'no_options': no_options, 'poll': poll})
    for user in user_options:
        polloption = poll.polloption_set.get(candidate=User.objects.get_by_natural_key(username=user))
        Vote.objects.create(voter=request.user, option=polloption)
    return render(request, 'polls/option.html', {'poll': poll})

class MyPollsView(generic.ListView):
    context_object_name = 'my_polls_list'
    template_name = 'polls/mypolls.html'
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated():
            return Poll.objects.filter(creator=user)
        else:
            raise Http404

def poll_option_view(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)

    if poll.vote_end <= timezone.now():
        return HttpResponseRedirect(reverse('polls:summary', kwargs={'poll_id': poll.id}))

    return render(request, 'polls/option.html', {'poll': poll})

def create_poll_view(request):
    if not request.user.is_authenticated():
        raise Http404
    maxvote_lower = False
    candidates_empty = True
    authorized_empty = True
    if request.method == "POST":
        form = PollCreateForm(request.POST)
        candidates = {}
        authorized = {}
        candidates_count = 0
        for user in User.objects.all():
            check_candidate = request.POST.getlist('{0}candidate'.format(user.username))
            check_authorized = request.POST.getlist('{0}authorized'.format(user.username))
            if check_candidate:
                candidates[user] = 'checked'
                candidates_count += 1
                candidates_empty = False
            else:
                candidates[user] = ''
            if check_authorized:
                authorized[user] = 'checked'
                authorized_empty = False
            else:
                authorized[user] = ''
        if form.is_valid():
            name = form.cleaned_data['name']
            pollstart = form.cleaned_data['pollstart']
            pollend = form.cleaned_data['pollend']
            maxvote = form.cleaned_data['maxvote']
            if candidates_count < int(maxvote):
                maxvote_lower = True
            elif candidates_empty == False and authorized_empty == False:
                created_poll = Poll.objects.create(name=name, creator=request.user, 
                    vote_start=pollstart, vote_end=pollend, max_vote_number=maxvote)
                for user, check in candidates.items():
                    if check == 'checked':
                        PollOption.objects.create(poll=created_poll, candidate=user)
                for user, check in authorized.items():
                    if check == 'checked':
                        Authorized.objects.create(poll=created_poll, user=user)
                return render(request, 'polls/create_summary.html', {'poll': created_poll})
    else:
        form = PollCreateForm()
        candidates = {}
        authorized = {}
        candidates_empty = False
        authorized_empty = False
        for user in User.objects.all():
            candidates[user] = ''
            authorized[user] = ''

    return render(request, 'polls/create.html', {'form': form, 'maxvote_lower': maxvote_lower,
        'candidates': candidates, 'authorized': authorized, 'candidates_empty': candidates_empty, 
        'authorized_empty': authorized_empty})

def change_poll_view(request, poll_id):
    maxvote_lower = False
    candidates_empty = True
    authorized_empty = True
    vote_started = False
    if request.method == "POST":
        poll = get_object_or_404(Poll, pk=poll_id)
        if timezone.now() > poll.vote_start and timezone.now() < poll.vote_end:
            vote_started = True
        if request.POST.get("update_users_button"):
            candidates = {}
            authorized = {}
            form = PollUsersChange(request.POST)
            candidates_count = 0
            for user in User.objects.all():
                check_candidate = request.POST.getlist('{0}candidate'.format(user.username))
                check_authorized = request.POST.getlist('{0}authorized'.format(user.username))
                if check_candidate:
                    candidates[user] = 'checked'
                    candidates_count += 1
                    candidates_empty = False
                else:
                    candidates[user] = ''
                if check_authorized:
                    authorized[user] = 'checked'
                    authorized_empty = False
                else:
                    authorized[user] = ''
            if form.is_valid():
                maxvote = form.cleaned_data['maxvote']
                if candidates_count < int(maxvote):
                    maxvote_lower = True
                elif candidates_empty == False and authorized_empty == False:
                    poll.max_vote_number = maxvote
                    PollOption.objects.filter(poll=poll).delete()
                    Authorized.objects.filter(poll=poll).delete()
                    for user, check in candidates.items():
                        if check == 'checked':
                            PollOption.objects.create(poll=poll, candidate=user)
                    for user, check in authorized.items():
                        if check == 'checked':
                            Authorized.objects.create(poll=poll, user=user)
                    poll.save()
                return HttpResponseRedirect(reverse('polls:mypolls'))
        elif request.POST.get("update_else_button"):
            form = StartedPollChange(request.POST)
            candidates = {}
            authorized = {}
            if form.is_valid():
                name = form.cleaned_data['name']
                pollstart = form.cleaned_data['pollstart']
                pollend = form.cleaned_data['pollend']
                poll.name = name
                poll.vote_start = pollstart
                poll.vote_end = pollend
                poll.save()
                return HttpResponseRedirect(reverse('polls:mypolls'))
        else:
            if not vote_started:
                poll.delete()
                return HttpResponseRedirect(reverse('polls:mypolls'))
    else:
        poll = get_object_or_404(Poll, pk=poll_id)
        if poll.creator != request.user:
            raise Http404
        if timezone.now() > poll.vote_start and timezone.now() < poll.vote_end:
            vote_started = True
        if vote_started:
            candidates = {}
            authorized = {}
            candidates_empty = False
            authorized_empty = False
            vote_start = localtime(poll.vote_start).strftime("%d/%m/%Y %H:%M:%S")
            vote_end = localtime(poll.vote_end).strftime("%d/%m/%Y %H:%M:%S")
            form = StartedPollChange({'name': poll.name, 'pollstart': vote_start, 'pollend': vote_end,
                'maxvote': poll.max_vote_number})
        else:
            vote_start = localtime(poll.vote_start).strftime("%d/%m/%Y %H:%M:%S")
            vote_end = localtime(poll.vote_end).strftime("%d/%m/%Y %H:%M:%S")
            form = PollChangeForm({'name': poll.name, 'pollstart': vote_start, 'pollend': vote_end,
                'maxvote': poll.max_vote_number})
            candidates = {}
            authorized = {}
            candidates_empty = False
            authorized_empty = False
            for option in PollOption.objects.filter(poll=poll):
                candidates[option.candidate] = 'checked'
            for auth in Authorized.objects.filter(poll=poll):

polls/templates/polls/active.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Trwające ankiety
{% endblock %}

{% block content %}
    {% if active_polls_list %}
        <ul>
            {% for poll in active_polls_list %}
                <div class="row">
                    <div class="col-md-6 item">
                        <div class="well well-poll">
                            <a href="/polls/{{ poll.id }}"><span class="glyphicon glyphicon-list-alt">
                                </span>  <b>{{ poll.name }}</b><br>Twórca:
                                <i>{{ poll.creator.first_name }} {{ poll.creator.last_name }}
                                ({{ poll.creator.username }})</i><br>Data zakończenia:
                                <i>{{ poll.vote_end|date:"d E o, G:i:s" }}</i><br>Dozwolona ilość zaznaczeń:
                                <i>{{ poll.max_vote_number}}</i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3 alert alert-info">
                Nie ma żadnych aktualnie trwających ankiet...
            </div>
        </div>
    {% endif %}
{% endblock %}

polls/templates/polls/change.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Zmiana ankiety
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <form action="{% url 'polls:change' poll_id %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.name.label }}:
                {% render_field form.name class="form-control" placeholder="np. Wybory starosty" %}
            </div>
        </div>
        {% if form.name.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.name.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.pollstart.label }}:
                {% render_field form.pollstart class="form-control" placeholder="DD/MM/RRRR GG:MM:SS" %}
            </div>
        </div>
        {% if form.pollstart.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.pollstart.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.pollend.label }}:
                {% render_field form.pollend class="form-control" placeholder="DD/MM/RRRR GG:MM:SS" %}
            </div> 
        </div>
        {% if form.pollend.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.pollend.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group text-center item">
                <div class="btn-group">
                    <input type="submit" name="update_else_button" value="Zmień dane ankiety" class="btn btn-primary">
                </div>
            </div>
        </div>
        {% if not vote_started %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group item">
                    {{ form.maxvote.label }}:
                    {% render_field form.maxvote class="form-control" placeholder="np. 2" %}
                </div>
            </div>
            {% if form.maxvote.errors %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 alert alert-danger">
                        {{ form.maxvote.errors.as_text }}<br>
                    </div>
                </div>
            {% endif %}
            {% if maxvote_lower %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 alert alert-danger">
                        * Ilość głosów nie może być większa od ilości kandydatów.<br>
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group item">
                    Kandydaci:<br>
                    <div class="scrollbox">
                        {% for user, checked in candidates.items %}
                            <input type="checkbox" name="{{ user.username }}candidate" {{ checked }}>
                            {{ user.first_name }} {{ user.last_name }} ({{ user.username }})<br>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% if candidates_empty %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 alert alert-danger">
                        * Przynajmniej jeden kandydat musi być zaznaczony.<br>
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group item">
                    Upoważnieni do głosowania:<br>
                    <div class="scrollbox">
                        {% for user, checked in authorized.items %}
                            <input type="checkbox" name="{{ user.username }}authorized" {{ checked }}>
                            {{ user.first_name }} {{ user.last_name }} ({{ user.username }})<br>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% if authorized_empty %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 alert alert-danger">
                        * Przynajmniej jedna upoważniona osoba musi być zaznaczona.<br>
                    </div> 
                </div>
            {% endif %}
            <br>
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group text-center item">
                    <div class="btn-group">
                        <input type="submit" name="update_users_button" value="Zmień kandydatów i upoważnionych" class="btn btn-primary">
                        <input type="submit" name="delete_button" value="Usuń ankietę" class="btn btn-danger">
                    </div>
                </div>
            </div>
        {% endif %}
    </form>
{% endblock %}

polls/templates/polls/create.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Tworzenie ankiety
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <form action="{% url 'polls:create' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.name.label }}:
                {% render_field form.name class="form-control" placeholder="np. Wybory starosty" %}
            </div>
        </div>
        {% if form.name.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.name.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.pollstart.label }}:
                {% render_field form.pollstart class="form-control" placeholder="DD/MM/RRRR GG:MM:SS" %}
            </div>
        </div>
        {% if form.pollstart.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.pollstart.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.pollend.label }}:
                {% render_field form.pollend class="form-control" placeholder="DD/MM/RRRR GG:MM:SS" %}
            </div>
        </div>
        {% if form.pollend.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.pollend.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.maxvote.label }}:
                {% render_field form.maxvote class="form-control" placeholder="np. 2" %}
            </div>
        </div>
        {% if form.maxvote.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.maxvote.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        {% if maxvote_lower %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    * Ilość głosów nie może być większa od ilości kandydatów.<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                Kandydaci:<br>
                <div class="scrollbox">
                    {% for user, checked in candidates.items %}
                        <input type="checkbox" name="{{ user.username }}candidate" {{ checked }}>
                        {{ user.first_name }} {{ user.last_name }} ({{ user.username }})<br>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if candidates_empty %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    * Przynajmniej jeden kandydat musi być zaznaczony.<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                Upoważnieni do głosowania:<br>
                <div class="scrollbox">
                    {% for user, checked in authorized.items %}
                        <input type="checkbox" name="{{ user.username }}authorized" {{ checked }}>
                        {{ user.first_name }} {{ user.last_name }} ({{ user.username }})<br>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if authorized_empty %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    * Przynajmniej jedna upoważniona osoba musi być zaznaczona.<br>
                </div>
            </div>
        {% endif %}
        <br>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group text-center item">
                <input type="submit" value="Stwórz ankietę" class="btn btn-primary">
            </div>
        </div>
    </form>
{% endblock %}

polls/templates/polls/create_summary.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Utworzono ankietę
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2 alert alert-success">
            Gratulacje!<br>
            Udało Ci się utworzyć ankietę o nazwie "{{ poll.name }}".<br>
            <a href="/polls/{{ poll.id }}/">Przejdź tutaj</a> aby wyświetlić ankietę lub
            <a href="/polls/{{ poll.id }}/change/">przejdź tutaj</a> aby zmienić ustawienia ankiety.
        </div>
    </div>
{% endblock %}

polls/templates/polls/ended.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Zakończone ankiety
{% endblock %}

{% block content %}
    {% load polls_tags %}
    {% if ended_polls_list %}
        <ul>
            {% for poll in ended_polls_list %}
                <div class="row">
                    <div class="col-md-6 item">
                        <div class="well well-poll">
                            <a href="/polls/{{ poll.id }}/summary"><span class="glyphicon glyphicon-list-alt">
                                </span>  <b>{{ poll.name }}</b><br>Twórca:
                                <i>{{ poll.creator.first_name }} {{ poll.creator.last_name }}
                                ({{ poll.creator.username }})</i><br>Zwycięzcy:<br>
                                {% poll_winner poll.id as poll_winner %}
                                <ul style="padding-left: 20px">
                                    {% if poll_winner %}
                                        {% for winner in poll_winner %}
                                            <li><i>{{ winner.first_name }} {{ winner.last_name }}
                                                ({{ winner.username }})</i></li>
                                        {% endfor %}
                                    {% else %}
                                        <i>brak</i>
                                    {% endif %}
                                </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3 alert alert-info">
                Nie ma żadnych zakończonych ankiet...
            </div>
        </div>
    {% endif %}
{% endblock %}

polls/templates/polls/incoming.html
{% extends "base.html" %}

{% block title %}
    Ankiety - Nadchodzące ankiety
{% endblock %}

{% block content %}
    {% if incoming_polls_list %}
        <ul>
            {% for poll in incoming_polls_list %}
                <div class="row">
                    <div class="col-md-6 item">
                        <div class="well well-poll">
                            <a href="/polls/{{ poll.id }}"><span class="glyphicon glyphicon-list-alt">
                                </span>  <b>{{ poll.name }}</b><br>Twórca:
                                <i>{{ poll.creator.first_name }} {{ poll.creator.last_name }}
                                ({{ poll.creator.username }})</i><br>Data rozpoczęcia:
                                <i>{{ poll.vote_start|date:"d E o, G:i:s" }}</i><br>Data zakończenia:
                                <i>{{ poll.vote_end|date:"d E o, G:i:s" }}</i><br>Dozwolona ilość zaznaczeń:
                                <i>{{ poll.max_vote_number}}</i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3 alert alert-info">
                Nie ma żadnych nadchodzących ankiet...
            </div>
        </div>
    {% endif %}
{% endblock %}

polls/templates/polls/summary.html
{% extends "base.html" %}

{% block title %}
    Ankieta "{{ poll.name }}" - Podsumowanie
{% endblock %}

{% block head %}
    {% load static %} 
    <charset="utf-8" />
    <script type="text/javascript" src="{% static "fusioncharts/fusioncharts.js" %}"></script>
    <script type="text/javascript" src="{% static "fusioncharts/themes/fusioncharts.theme.fint.js" %}"></script>
{% endblock %}

{% block content %}
    {% csrf_token %}
    {% load polls_tags %}
    {% poll_attendance poll.id as poll_attendance %}
    {% poll_winner poll.id as poll_winner %}
    <div class="row">
        <div class="col-md-offset-2 item">
            <div id="chart-1">{{ output|safe }}</div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 input-group item">
            <div class="well well-poll">
                <b>Zwycięzcy:</b><br>
                <ul>
                    {% if poll_winner %}
                        {% for winner in poll_winner %}
                            <li><i>{{ winner.first_name }} {{ winner.last_name }}
                            ({{ winner.username }})</i></li>
                        {% endfor %}
                    {% else %}
                        <i>brak</i>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 alert alert-info item">
            <b>Frekwencja:</b> {{ poll_attendance|floatformat:2 }}%
        </div>
    </div>
{% endblock %}

polls/templates/polls/vote.html
{% extends "base.html" %}

{% block title %}
    Ankieta "{{ poll.name }}" - Głosowanie
{% endblock %}

{% block content %}
    {% if vote_timeout %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3 item alert alert-warning">
                Głosowanie na tą ankietę zostało już zakończone!<br>
                <a href="/polls/{{ poll.id }}/summary">Przejdź tutaj</a> aby zobaczyć wyniki.
            </div>
        </div>
    {% else %}
        {% if too_many_options %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Zaznaczono zbyt dużo opcji.<br>
                </div>
            </div>
        {% endif %}
        {% if no_options %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Musisz zaznaczyć przynajmniej jedną opcję.<br>
                </div>
            </div>
        {% endif %}
        <form action="{% url 'polls:votemake' poll.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group item">
                    <b>Wybierz kandydata/-ów:</b><br><br>
                    <div class="scrollbox-vote">
                        {% for option in poll.polloption_set.all %}
                            <input type="checkbox" name="option" value="{{ option.candidate }}" />
                            {{ option.candidate.first_name }} {{ option.candidate.last_name }}
                            ({{ option.candidate.username }})<br>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4 item">
                    <i>Maksymalna dozwolona liczba głosów: <b>{{ poll.max_vote_number }}</b></i><br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group text-center item">
                    <input type="submit" value="Zagłosuj" class="btn btn-primary">
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}