SWybor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'views.bad_request'
# handler403 = 'views.permission_denied'
# handler404 = 'views.page_not_found'
# handler500 = 'views.server_error'

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^profile/', include('profuzyt.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^maps/', include('maps.urls')),
    url(r'^news/', include('blog.urls')),
   
]

blog/urls.py
# ~*~ coding: utf-8 ~*~

from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.main_page, name='main'),
    #url(r'^$', main_page),
    # Если передан id поста, то отдаем управление get_post вьюхе
   url(r'^post/([0-9]{1,5})', views.get_post,name='post'),
    #url(r'^post/([0-9]{1,5})', views.poll_summary, name='summary'),
    
]

loginsys/urls.py
from django.conf.urls import url

from . import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register_view, name='register'),
    url(r'^register/(?P<username>[a-z0-9]+)/(?P<register_code>[0-9A-Z]{16,})/$', 
        views.register_confirmation_view, name='register_confirm'),
    url(r'^register/resend', views.register_resend_view, name='register_resend'),
]

loginsys/models.py
from django.db import models
from django.contrib.auth.models import User

class UserConfirmation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_confirmed = models.BooleanField()
    confirm_code = models.CharField(max_length=16)
    def __str__(self):
        if self.is_confirmed:
            return "User:{" + self.user.username + "} confirmed"
        else:
            return "User:{" + self.user.username + "} not confirmed"

loginsys/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
import re

class LoginForm(forms.Form):
    username = forms.CharField(label='Nazwa użytkownika', required=False, max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, label='Hasło', required=False, max_length=30)

    def clean_username(self):
        data = self.cleaned_data['username']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        return data

    def clean_password(self):
        data = self.cleaned_data['password']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        return data

class RegisterForm(forms.Form):
    firstname = forms.CharField(label='Imię', required=False, max_length=30)
    lastname = forms.CharField(label='Nazwisko', required=False, max_length=30)
    username = forms.CharField(label='Nazwa użytkownika', required=False, max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, label='Hasło', required=False, max_length=30)
    repeatpassword = forms.CharField(widget=forms.PasswordInput, label='Powtórz hasło', required=False, max_length=30)
    email = forms.CharField(label='Adres e-mail', required=False)
    captcha = CaptchaField(label='Kod CAPTCHA')

    firstname_regex = re.compile("^[ĘÓĄŚŁŻŹĆŃA-Z][ęóąśłżźćńa-z]+$")
    lastname_regex = re.compile("^[ĘÓĄŚŁŻŹĆŃA-Z][ęóąśłżźćńa-z]+$")
    username_regex = re.compile("^[a-z0-9]+$")
    min_username_length = 6
    password_regex = re.compile("^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@.\+\-_])[A-Za-z\d@.+-_]+$")
    min_password_length = 6

    def clean_firstname(self):
        data = self.cleaned_data['firstname']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.firstname_regex.match(data):
            raise forms.ValidationError(
                "Niepoprawny format imienia."
            )
        return data

    def clean_lastname(self):
        data = self.cleaned_data['lastname']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.lastname_regex.match(data):
            raise forms.ValidationError(
                "Niepoprawny format nazwiska."
            )
        return data

    def clean_username(self):
        data = self.cleaned_data['username']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.username_regex.match(data):
            raise forms.ValidationError(
                "Nazwa użytkownika może składać się tylko z małych liter i cyfer."
            )
        if len(data) < self.min_username_length:
            raise forms.ValidationError(
                "Długośc nazwy użytkownika musi mieć minimum 6 znaków."
            )
        return data

    def clean_password(self):
        data = self.cleaned_data['password']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if not self.password_regex.match(data):
            raise forms.ValidationError(
                "Hasło może się składać tylko z liter, dużych liter, cyfr i @/./+/-/_ " + 
                "i musi mieć po jednym z tych znaków."
            )
        if len(data) < self.min_password_length:
            raise forms.ValidationError(
                "Długośc hasła musi mieć mieć minimum 6 znaków."
            )
        return data

    def clean_repeatpassword(self):
        data = self.cleaned_data['repeatpassword']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        if 'password' in self.cleaned_data and data != self.cleaned_data['password']:
            raise forms.ValidationError(
                "Podane hasła muszą do siebie pasować."
            )
        return data

    def clean_email(self):
        data = self.cleaned_data['email']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        try:
            validate_email(data)
        except ValidationError as e:
            raise forms.ValidationError(
                "Nie poprawny adres e-mail."
            )
        return data

    def clean_captcha(self):
        data = self.cleaned_data['captcha']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        return data

class RegisterResendForm(forms.Form):
    email = forms.CharField(label='Adres e-mail', required=False)

    def clean_email(self):
        data = self.cleaned_data['email']
        if not data:
            raise forms.ValidationError(
                "Te pole musi zostać uzupełnione."
            )
        try:
            validate_email(data)
        except ValidationError as e:
            raise forms.ValidationError(
                "Nie poprawny adres e-mail."
            )
        return data

loginsys/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import LoginForm, RegisterForm, RegisterResendForm
from .models import UserConfirmation
from django.template import RequestContext
import random, string
from .e_sen import send_confirmation_email

def login_view(request):
    user_not_exists = False
    not_confirmed = False
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if not user:
                user_not_exists = True
            else:
                userconf = UserConfirmation.objects.filter(user=user).first()
                if userconf is None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('home'))
                if userconf.is_confirmed:
                    login(request, user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    not_confirmed = True
    else:
        form = LoginForm()

    return render(request, 'loginsys/login.html', {'form': form, 'user_not_exists': user_not_exists,
        'not_confirmed': not_confirmed})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register_view(request):
    username_exists = False
    email_exists = False
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            if username in User.objects.all().values_list('username', flat=True):
                username_exists = True
            elif email in User.objects.all().values_list('email', flat=True):
                email_exists = True
            else:
                user = User.objects.create_user(username=username, email=email, password=password, 
                    first_name=firstname, last_name=lastname)
                random_code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=16))
                UserConfirmation.objects.create(user=user, is_confirmed=False, confirm_code=random_code)
                send_confirmation_email(user.email, user.username, random_code)
                context = {
                    'username': user.username,
                    'firstname': user.first_name,
                    'lastname': user.last_name,
                    'email': user.email,
                }
                return render(request, 'loginsys/register_complete.html', context)
    else:
        form = RegisterForm()

    return render(request, 'loginsys/register.html', {'form': form, 
        'username_exists': username_exists, 'email_exists': email_exists})

def register_resend_view(request):
    email_exists = True
    user_confirmed = False
    was_post = False
    if request.method == "POST":
        form = RegisterResendForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if email not in User.objects.all().values_list('email', flat=True):
                email_exists = False
            else:
                user = get_object_or_404(User, email=email)
                userconf = get_object_or_404(UserConfirmation, user=user)
                if UserConfirmation.objects.get(user=user).is_confirmed:
                    user_confirmed = True
                else:
                    was_post = True
                    send_confirmation_email(user.email, user.username, userconf.confirm_code)
                    return render(request, 'loginsys/register_resend.html', {'email_exists': email_exists, 
                        'was_post': was_post, 'user_confirmed': user_confirmed, 'email': email})
    else:
        form = RegisterResendForm()

    return render(request, 'loginsys/register_resend.html', {'form': form, 'email_exists': email_exists, 
        'was_post': was_post, 'user_confirmed': user_confirmed})
    
def register_confirmation_view(request, username, register_code):
    user = get_object_or_404(User, username=username)
    userconf = get_object_or_404(UserConfirmation, user=user)
    confirmed = False
    print("DANY KOD: {0} KOD UZYTKOWNIKA {1}".format(userconf.confirm_code, register_code))
    if userconf.is_confirmed:
        confirmed = True
    elif userconf.confirm_code != register_code:
        raise Http404
    else:
        userconf.is_confirmed = True
        userconf.save()
        login(request, user)

    return render(request, 'loginsys/register_confirm.html', {'confirmed': confirmed})

loginsys/templates/loginsys/login.html
{% extends "base.html" %}

{% block title %}
    Logowanie
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <form action="{% url 'loginsys:login' %}" method="post">
        {% csrf_token %}
        {% if user_not_exists %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Błąd logowania!<br>Podana nazwa użytkownika lub hasło jest błędne!<br>
                    Sprawdź ich poprawność.
                </div>
            </div>
        {% endif %}
        {% if not_confirmed %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Te konto jest nieaktywowane!<br>
                    Upewnij się czy wiadomość z potwierdzeniem nie trafiła do skrzynki SPAM.<br>
                    Nie dostałes wiadomości?
                    <a href="/auth/register/resend">Kliknij tutaj</a>
                    aby wysłać ją jeszcze raz.<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                {% render_field form.username class="form-control" placeholder=form.username.label %}
            </div>
        </div>
        {% if form.username.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.username.errors.as_text }}
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                {% render_field form.password class="form-control" placeholder=form.password.label %}
            </div>
        </div>
        {% if form.password.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.password.errors.as_text }}
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center item">
                <input type="submit" value="Zaloguj się" class="btn btn-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 item">
                <br>Nie masz konta? <a href="/auth/register">Kliknij tutaj</a> aby się zarejestrować.
            </div>
        </div>
    </form>
{% endblock %}

loginsys/templates/loginsys/register.html
{% extends "base.html" %}

{% block title %}
    Rejestracja
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <form action="{% url 'loginsys:register' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.firstname.label }}:
                {% render_field form.firstname class="form-control" placeholder="np. Jan" %}
            </div>
        </div>
        {% if form.firstname.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.firstname.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.lastname.label }}:
                {% render_field form.lastname class="form-control" placeholder="np. Kowalski" %}
            </div>
        </div>
        {% if form.lastname.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.lastname.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.username.label }}:
                {% render_field form.username class="form-control" placeholder="np. jkowalski" %}
            </div>
        </div>
        {% if form.username.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.username.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        {% if username_exists %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Istnieje już konto z taką samą nazwą użytkownika.<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.password.label }}:
                {% render_field form.password class="form-control" placeholder="np. Jkowalski3_" %}
            </div>
        </div>
        {% if form.password.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.password.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.repeatpassword.label }}:
                {% render_field form.repeatpassword class="form-control" placeholder="np. Jkowalski3_" %}
            </div>
        </div>
        {% if form.repeatpassword.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.repeatpassword.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 input-group item">
                {{ form.email.label }}:
                {% render_field form.email class="form-control" placeholder="np. jkowalski@wp.pl" %}
            </div>
        </div>
        {% if form.email.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.email.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        {% if email_exists %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    Istnieje już konto z takim samym adresem e-mail.<br>
                </div>
            </div>
        {% endif %}
        <div class="col-md-4 col-md-offset-4 input-group item">
            {{ form.captcha.label }}:<br>
            {{ form.captcha }}
        </div>
        {% if form.captcha.errors %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 alert alert-danger">
                    {{ form.captcha.errors.as_text }}<br>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center item">
                <input type="submit" value="Zarejestruj się" class="btn btn-primary">
            </div>
        </div>
    </form>
{% endblock %}

loginsys/templates/loginsys/register_complete.html
{% extends "base.html" %}

{% block title %}
    Rejestracja - Rejestracja zakończona pomyślnie
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2 alert alert-success">
            Gratulacje!<br>
            Udało Ci się utworzyć konto, {{ firstname }} {{ lastname }}!<br>
            Wiadomość z linkiem potwierdzającym konto została wysłana na adres {{ email }}.<br>
            Upewnij się czy wiadomość nie trafiła do skrzynki SPAM.<br>
            Nie dostałes wiadomości?
            <a href="/auth/register/resend">Kliknij tutaj</a>
            aby wysłać ją jeszcze raz.
        </div>
    </div>
{% endblock %}

loginsys/templates/loginsys/register_confirm.html
{% extends "base.html" %}

{% block title %}
    Rejestracja - Potwierdzenie rejestracji
{% endblock %}

{% block content %}
    {% if confirmed %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 alert alert-danger">
                Konto jest już aktywne!
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 alert alert-success">
                Dziękujemy za potwierdzenie swojego konta!<br>
                Zostałeś automatycznie na nie zalogowany.
            </div>
        </div>
    {% endif %}
{% endblock %}

loginsys/templates/loginsys/register_resend.html
{% extends "base.html" %}

{% block title %}
    Rejestracja - Ponowne wysłanie linku aktywującego
{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    {% if not email_exists %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 alert alert-danger">
                Nie istnieje użytkownik o takim adresie email!<br>
                Sprawdź poprawność wpisanego adresu.<br>
            </div>
        </div>
    {% endif %}
    {% if user_confirmed %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 alert alert-danger">
                Konto o danym adresie jest już aktywne!<br>
            </div>
        </div>
    {% endif %}
    {% if was_post %}
        <div class="row">
            <div class="col-md-8 col-md-offset-2 alert alert-success">
                Wiadomość z linkiem potwierdzającym konto została wysłana na adres {{ email }}.<br>
                Nie dostałes wiadomości?
                <a href="/auth/register/resend">Kliknij tutaj</a>
                aby wysłać ją jeszcze raz.
            </div>
        </div>
    {% else %}
        <form action="{% url 'loginsys:register_resend' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 input-group item">
                    Wprowadź adres e-mail podany przy rejestracji:
                    {% render_field form.email class="form-control" placeholder=form.email.label %}
                </div>
            </div>
            {% if form.email.errors %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 alert alert-danger">
                        {{ form.email.errors.as_text }}<br>
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4 text-center item">
                    <input type="submit" value="Wyślij" class="btn btn-primary">
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}